-- ============================================================================
-- Migration 153: Voice Rooms (FreeTalk) — DESCARTADA
--
-- Esta abordagem (tabelas voice_rooms e voice_room_members separadas) foi
-- descartada em favor da Migration 154, que integra o modelo de palco
-- diretamente na tabela call_participants existente via stage_role e
-- hand_raised, unificando o sistema em uma única estrutura.
--
-- Esta migration é intencionalmente vazia para preservar a sequência numérica.
-- ============================================================================
