-- =============================================================================
-- Migration 237 — Corrigir temas built-in para espelhar o código Flutter
--
-- A migration 096 inseriu temas com valores incorretos (principal era light,
-- midnight tinha cores erradas). Esta migration substitui os 3 temas com os
-- tokens exatos que estavam hardcoded em nexus_themes.dart.
--
-- Após esta migration, o Flutter poderá remover nexus_themes.dart e usar
-- exclusivamente o banco como fonte de temas.
-- =============================================================================

-- ─── PRINCIPAL (Dark — Azul-marinho + Ciano) ──────────────────────────────────
UPDATE public.app_themes
SET
  name        = 'Principal',
  description = 'O visual original do NexusHub — azul-marinho e ciano.',
  base_mode   = 'dark',
  is_builtin  = TRUE,
  is_active   = TRUE,
  sort_order  = 0,
  colors = '{
    "backgroundPrimary":        "#0D1B2A",
    "backgroundSecondary":      "#0A1628",
    "surfacePrimary":           "#1B2838",
    "surfaceSecondary":         "#213040",
    "cardBackground":           "#213040",
    "cardBackgroundElevated":   "#2A3A4E",
    "modalBackground":          "#1B2838",
    "overlayColor":             "#CC000000",
    "textPrimary":              "#F2F2F2",
    "textSecondary":            "#8899AA",
    "textHint":                 "#8A9FB0",
    "textDisabled":             "#3A4A5A",
    "iconPrimary":              "#F2F2F2",
    "iconSecondary":            "#8899AA",
    "iconDisabled":             "#3A4A5A",
    "accentPrimary":            "#00BCD4",
    "accentSecondary":          "#4DD0E1",
    "buttonPrimaryBackground":  "#1A9E4A",
    "buttonPrimaryForeground":  "#FFFFFF",
    "buttonSecondaryBackground":"#213040",
    "buttonSecondaryForeground":"#00BCD4",
    "buttonDestructiveBackground":"#E53935",
    "buttonDestructiveForeground":"#FFFFFF",
    "success":                  "#69F0AE",
    "successContainer":         "#1A3A2A",
    "error":                    "#E53935",
    "errorContainer":           "#3A1A1A",
    "warning":                  "#FF9800",
    "warningContainer":         "#3A2A10",
    "info":                     "#2979FF",
    "infoContainer":            "#1A2A3A",
    "borderPrimary":            "#2A3A50",
    "borderSubtle":             "#1E2E40",
    "borderFocus":              "#00BCD4",
    "inputBackground":          "#213040",
    "inputBorder":              "#2A3A50",
    "inputHint":                "#8A9FB0",
    "selectedState":            "#00BCD4",
    "disabledState":            "#2A3A50",
    "bottomNavBackground":      "#0A1628",
    "bottomNavSelectedItem":    "#FFFFFF",
    "bottomNavUnselectedItem":  "#6A7D8E",
    "appBarBackground":         "#0D1B2A",
    "appBarForeground":         "#F2F2F2",
    "drawerBackground":         "#1B2838",
    "drawerHeaderBackground":   "#213040",
    "drawerSidebarBackground":  "#000000",
    "chipBackground":           "#213040",
    "chipSelectedBackground":   "#1A3A4A",
    "chipText":                 "#8899AA",
    "chipSelectedText":         "#00BCD4",
    "divider":                  "#2A3A50",
    "shimmerBase":              "#213040",
    "shimmerHighlight":         "#2A3A4E",
    "levelBadgeBackground":     "#1565C0",
    "levelBadgeForeground":     "#0D1B2A",
    "coinColor":                "#FFD700",
    "onlineIndicator":          "#2DBE60",
    "previewAccent":            "#00BCD4"
  }'::jsonb,
  gradients = '{
    "primaryGradient":   {"colors": ["#1A9E4A", "#00BCD4"], "begin": "topLeft",    "end": "bottomRight"},
    "accentGradient":    {"colors": ["#00BCD4", "#4DD0E1"], "begin": "topLeft",    "end": "bottomRight"},
    "fabGradient":       {"colors": ["#E91E63", "#FF5C8D"], "begin": "topLeft",    "end": "bottomRight"},
    "streakGradient":    {"colors": ["#FF9800", "#FFB74D"], "begin": "centerLeft", "end": "centerRight"},
    "walletGradient":    {"colors": ["#4FC3F7", "#29B6F6"], "begin": "topCenter",  "end": "bottomCenter"},
    "aminoPlusGradient": {"colors": ["#FF9800", "#FFB74D"], "begin": "centerLeft", "end": "centerRight"}
  }'::jsonb,
  shadows = '{
    "cardShadow":   [{"color": "#33000000", "blurRadius": 8,  "offsetX": 0, "offsetY": 2}],
    "modalShadow":  [{"color": "#4D000000", "blurRadius": 24, "offsetX": 0, "offsetY": 8}],
    "buttonShadow": [{"color": "#401A9E4A", "blurRadius": 8,  "offsetX": 0, "offsetY": 3}]
  }'::jsonb,
  opacities = '{
    "overlayOpacity":  0.8,
    "disabledOpacity": 0.38
  }'::jsonb
WHERE slug = 'principal';

-- ─── MIDNIGHT (Dark — Preto + Roxo Vibrante) ──────────────────────────────────
UPDATE public.app_themes
SET
  name        = 'Midnight',
  description = 'Escuro, premium e noturno — roxo vibrante sobre o preto.',
  base_mode   = 'dark',
  is_builtin  = TRUE,
  is_active   = TRUE,
  sort_order  = 1,
  colors = '{
    "backgroundPrimary":        "#0A0A0F",
    "backgroundSecondary":      "#0E0C18",
    "surfacePrimary":           "#15121F",
    "surfaceSecondary":         "#1E1830",
    "cardBackground":           "#1A1528",
    "cardBackgroundElevated":   "#241D38",
    "modalBackground":          "#1E1830",
    "overlayColor":             "#B3100D1A",
    "textPrimary":              "#F2F0FF",
    "textSecondary":            "#B0A8D0",
    "textHint":                 "#8A80A8",
    "textDisabled":             "#3A3050",
    "iconPrimary":              "#F2F0FF",
    "iconSecondary":            "#B0A8D0",
    "iconDisabled":             "#3A3050",
    "accentPrimary":            "#9B59F5",
    "accentSecondary":          "#BB86FC",
    "buttonPrimaryBackground":  "#9B59F5",
    "buttonPrimaryForeground":  "#FFFFFF",
    "buttonSecondaryBackground":"#2A1F45",
    "buttonSecondaryForeground":"#BB86FC",
    "buttonDestructiveBackground":"#FF6B81",
    "buttonDestructiveForeground":"#1A0A10",
    "success":                  "#69F0AE",
    "successContainer":         "#1A3028",
    "error":                    "#FF6B81",
    "errorContainer":           "#3A1A22",
    "warning":                  "#FFB74D",
    "warningContainer":         "#3A2A10",
    "info":                     "#7986CB",
    "infoContainer":            "#1A1E38",
    "borderPrimary":            "#556B4FA0",
    "borderSubtle":             "#2A6B4FA0",
    "borderFocus":              "#9B59F5",
    "inputBackground":          "#1A1528",
    "inputBorder":              "#556B4FA0",
    "inputHint":                "#8A80A8",
    "selectedState":            "#9B59F5",
    "disabledState":            "#3A3050",
    "bottomNavBackground":      "#0A0A0F",
    "bottomNavSelectedItem":    "#BB86FC",
    "bottomNavUnselectedItem":  "#6A5F88",
    "appBarBackground":         "#0A0A0F",
    "appBarForeground":         "#F2F0FF",
    "drawerBackground":         "#15121F",
    "drawerHeaderBackground":   "#1E1830",
    "drawerSidebarBackground":  "#07050F",
    "chipBackground":           "#1E1830",
    "chipSelectedBackground":   "#3A2A60",
    "chipText":                 "#B0A8D0",
    "chipSelectedText":         "#BB86FC",
    "divider":                  "#336B4FA0",
    "shimmerBase":              "#1A1528",
    "shimmerHighlight":         "#241D38",
    "levelBadgeBackground":     "#9B59F5",
    "levelBadgeForeground":     "#1A0A2E",
    "coinColor":                "#FFD700",
    "onlineIndicator":          "#69F0AE",
    "previewAccent":            "#9B59F5"
  }'::jsonb,
  gradients = '{
    "primaryGradient":   {"colors": ["#9B59F5", "#BB86FC"], "begin": "topLeft",    "end": "bottomRight"},
    "accentGradient":    {"colors": ["#7B2FBE", "#9B59F5"], "begin": "topLeft",    "end": "bottomRight"},
    "fabGradient":       {"colors": ["#9B59F5", "#BB86FC"], "begin": "topLeft",    "end": "bottomRight"},
    "streakGradient":    {"colors": ["#FF9800", "#FFB74D"], "begin": "centerLeft", "end": "centerRight"},
    "walletGradient":    {"colors": ["#9B59F5", "#BB86FC"], "begin": "topCenter",  "end": "bottomCenter"},
    "aminoPlusGradient": {"colors": ["#9B59F5", "#BB86FC"], "begin": "centerLeft", "end": "centerRight"}
  }'::jsonb,
  shadows = '{
    "cardShadow":   [{"color": "#339B59F5", "blurRadius": 12, "offsetX": 0, "offsetY": 4}],
    "modalShadow":  [{"color": "#4D9B59F5", "blurRadius": 24, "offsetX": 0, "offsetY": 8}],
    "buttonShadow": [{"color": "#409B59F5", "blurRadius": 10, "offsetX": 0, "offsetY": 4}]
  }'::jsonb,
  opacities = '{
    "overlayOpacity":  0.7,
    "disabledOpacity": 0.38
  }'::jsonb
WHERE slug = 'midnight';

-- ─── GREENLEAF (Light — Verde Natural) ────────────────────────────────────────
UPDATE public.app_themes
SET
  name        = 'GreenLeaf',
  description = 'Fresco, limpo e natural — verde vibrante sobre fundo claro.',
  base_mode   = 'light',
  is_builtin  = TRUE,
  is_active   = TRUE,
  sort_order  = 2,
  colors = '{
    "backgroundPrimary":        "#F0F7F2",
    "backgroundSecondary":      "#E4F2E6",
    "surfacePrimary":           "#FAFDFА",
    "surfaceSecondary":         "#E4F2E6",
    "cardBackground":           "#FAFDFА",
    "cardBackgroundElevated":   "#FFFFFF",
    "modalBackground":          "#FAFDFА",
    "overlayColor":             "#661A3A1E",
    "textPrimary":              "#0F1F11",
    "textSecondary":            "#2E4A34",
    "textHint":                 "#4A6A52",
    "textDisabled":             "#B0CCB4",
    "iconPrimary":              "#0F1F11",
    "iconSecondary":            "#2E4A34",
    "iconDisabled":             "#B0CCB4",
    "accentPrimary":            "#1A7A3C",
    "accentSecondary":          "#2E9E50",
    "buttonPrimaryBackground":  "#1A7A3C",
    "buttonPrimaryForeground":  "#FFFFFF",
    "buttonSecondaryBackground":"#2E9E50",
    "buttonSecondaryForeground":"#FFFFFF",
    "buttonDestructiveBackground":"#B71C1C",
    "buttonDestructiveForeground":"#FFFFFF",
    "success":                  "#2E9E50",
    "successContainer":         "#D8F0DC",
    "error":                    "#B71C1C",
    "errorContainer":           "#FFEBEE",
    "warning":                  "#A85200",
    "warningContainer":         "#FFF3E0",
    "info":                     "#1565C0",
    "infoContainer":            "#E3F2FD",
    "borderPrimary":            "#9ECBA8",
    "borderSubtle":             "#C4DEC8",
    "borderFocus":              "#1A7A3C",
    "inputBackground":          "#E4F2E6",
    "inputBorder":              "#9ECBA8",
    "inputHint":                "#4A6A52",
    "selectedState":            "#1A7A3C",
    "disabledState":            "#B0CCB4",
    "bottomNavBackground":      "#FFFFFF",
    "bottomNavSelectedItem":    "#1A7A3C",
    "bottomNavUnselectedItem":  "#4A6650",
    "appBarBackground":         "#FAFDFА",
    "appBarForeground":         "#0F1F11",
    "drawerBackground":         "#F0F7F2",
    "drawerHeaderBackground":   "#D8EDD8",
    "drawerSidebarBackground":  "#2D4A30",
    "chipBackground":           "#D0E8D4",
    "chipSelectedBackground":   "#1A7A3C",
    "chipText":                 "#1A3A22",
    "chipSelectedText":         "#FFFFFF",
    "divider":                  "#C4DEC8",
    "shimmerBase":              "#DCE8DF",
    "shimmerHighlight":         "#EDF7EE",
    "levelBadgeBackground":     "#1A7A3C",
    "levelBadgeForeground":     "#FFFFFF",
    "coinColor":                "#B8860B",
    "onlineIndicator":          "#2E9E50",
    "previewAccent":            "#1A7A3C"
  }'::jsonb,
  gradients = '{
    "primaryGradient":   {"colors": ["#1A7A3C", "#2E9E50"], "begin": "topLeft",    "end": "bottomRight"},
    "accentGradient":    {"colors": ["#2E9E50", "#56C27A"], "begin": "topLeft",    "end": "bottomRight"},
    "fabGradient":       {"colors": ["#1A7A3C", "#2E9E50"], "begin": "topLeft",    "end": "bottomRight"},
    "streakGradient":    {"colors": ["#2E9E50", "#56C27A"], "begin": "centerLeft", "end": "centerRight"},
    "walletGradient":    {"colors": ["#1A7A3C", "#2E9E50"], "begin": "topCenter",  "end": "bottomCenter"},
    "aminoPlusGradient": {"colors": ["#1A7A3C", "#2E9E50"], "begin": "centerLeft", "end": "centerRight"}
  }'::jsonb,
  shadows = '{
    "cardShadow":   [{"color": "#221A7A3C", "blurRadius": 6,  "offsetX": 0, "offsetY": 1},
                     {"color": "#0F000000", "blurRadius": 2,  "offsetX": 0, "offsetY": 1}],
    "modalShadow":  [{"color": "#2E1A7A3C", "blurRadius": 20, "offsetX": 0, "offsetY": 8}],
    "buttonShadow": [{"color": "#401A7A3C", "blurRadius": 8,  "offsetX": 0, "offsetY": 3}]
  }'::jsonb,
  opacities = '{
    "overlayOpacity":  0.4,
    "disabledOpacity": 0.38
  }'::jsonb
WHERE slug = 'green_leaf';
