// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
import 'core/l10n/locale_provider.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      final s = getStrings();
      throw UnsupportedError(
        s.defaultFirebaseOptionsWebNotConfigured
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      final s = getStrings();
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          s.defaultFirebaseOptionsIosNotConfigured
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          s.defaultFirebaseOptionsMacosNotConfigured
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          s.defaultFirebaseOptionsWindowsNotConfigured
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          s.defaultFirebaseOptionsLinuxNotConfigured
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          s.defaultFirebaseOptionsNotSupported,
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBxxx_placeholder_firebase_key',
    appId: '1:884602945431:android:784997bcf65af896e20ed2',
    messagingSenderId: '884602945431',
    projectId: 'aminexus-8dabd',
    storageBucket: 'aminexus-8dabd.firebasestorage.app',
  );
}
